### ISSUE TITLE
IE8 support: use 0rem instead of 0px

### ISSUE THREAD

**Issue by fvsch** [colourgarden/avalanche#11]
Right now in IE8 it's likely that all grid content will vanish into thin air because of the `font-size:0px;` (we're using this technique a lot at work and blocks where all the text disappears because of that is a common occurrence).

A simple solution would be to use `font-size:0rem;` instead. That way, IE8 will ignore the zero font-size, and content will be displayed, even though the last item in a row or grid will often wrap.
In my book, visible content with broken layout is a better degradation than invisible content. :)

Post-processors might still convert it to `font-size: 0px; font-size: 0rem;` which would fix the layout as well.

**Comment by colourgarden** [comment]
@fvsch Hi Florent. This seems like a really good suggestion. I'll run some tests to make sure it works as expected and merge in. Thanks for your support of Avalanche!

**Comment by colourgarden** [comment]
Apologies for the delay but this has now been added into the project - https://github.com/colourgarden/avalanche/releases/tag/1.1.1
@fvsch
