### ISSUE TITLE
Class names should not begin with a digit

### ISSUE THREAD

**Issue by skube** [colourgarden/avalanche#14]
I was under the impression class names could not _start_ with a number, even though it may technically work in some browsers:
http://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors

**Comment by colourgarden** [comment]
Hi. Please refer to a [previous issue](https://github.com/colourgarden/avalanche/issues/7) covering this point. As mentioned there, would an option for transposing class names into "one-of-four" be of use?

Thanks for supporting Avalanche. Tom
