### ISSUE TITLE
add pre-built file on npm

### ISSUE THREAD

**Issue by maruilian11** [colourgarden/avalanche#17]
hi, recently we want to add your lib on https://cdnjs.com, could you please also consider adding pre-built file on npm package so that we can use npm auto-update config to add every released version.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6680

**Comment by colourgarden** [comment]
@marulian11 Hi. Thanks for alerting me to this. I use cdnjs myself so I'd be honoured to have it added! I'm currently on vacation and unable to sort a fix but I'll add it next week and update this and the cdnjs issue. Thanks again, Tom

**Comment by maruilian11** [comment]
thank you very much! :smile:

**Comment by colourgarden** [comment]
Avalanche is now available on cdnjs!
https://cdnjs.com/libraries/avalanche-css

**Comment by maruilian11** [comment]
great! :+1:
