### ISSUE TITLE
fractions with double figures 

### ISSUE THREAD

**Issue by compton01** [colourgarden/avalanche#18]
i'm using a 12 column grid with fractions, when i use .10/12 or .11/12 the class name is not found, 

this is how they are outputted

.\310\/12 { width: 83.33333%; }

.\311\/12 { width: 91.66667%; }

but they need to be like this 

.\31\30\/12 { width: 83.33333%; }

.\31\31\/12 { width: 91.66667%; }

**Comment by colourgarden** [comment]
Hi @compton01. I've published a fix for this and it is included as part of the latest 1.1.0 release. Thanks for pointing it out and supporting Avalanche.
