### ISSUE TITLE
Fraction class generation not working over 9

### ISSUE THREAD

**Issue by nicaille** [colourgarden/avalanche#20]
Hello 
First Thank you for your great work on avalanche! 

I've a problem when using it with $av-widths equal at 12. All classes are generated exception of 10/12, 11/12, 12/12. I think it is because of the Ascii code generated by \310 => .°, \311
Do you have any idea or already know the problem?

Thank you in advance

**Comment by colourgarden** [comment]
@nicaille Hi. Thanks for your interest in Avalanche!

How are you compiling your Sass? That class name doesn't look properly formed. Issue #18 fixed a previous bug where double-figure fraction class names weren't being properly generated so please also make sure you're using v1.1.0 of Avalanche.

**Comment by nicaille** [comment]
Hi, thanks for answering!
About the compiling, I use "Prepros" with auto prefix option and the "expand mode" selected.
I'm already using the V1.1.0 ;-(

Could you please give a try with the following configuration and let me know if class 10/12, 11/12 & 12/12 are working on your side?

**$av-widths: (  2,  3,  4,  12 ) !default;**

TY
++

**Comment by colourgarden** [comment]
@nicaille Could you upload your Sass files and compiled CSS files so I can take a look? I downloaded Prepros and tried it using your configuration and it was compiling ok for me. Thanks.

**Comment by nicaille** [comment]
Hello

Files are attached THANK YOU VERY MUCH

++

**Comment by nicaille** [comment]
Here are files if easier than by email:
[css.zip](https://github.com/colourgarden/avalanche/files/247076/css.zip)

**Comment by colourgarden** [comment]
Looking at your avalanche.css file, there are classes for 10/12 and 11/12 on lines 115-121 (these are escaped with back-slashes). I did a quick HTML test page using your stylesheet and the grid was functioning correctly. Are any of the grid classes working for you when in a HTML page in a browser?

**Comment by nicaille** [comment]
It is working now ! But can’t explain… 

TY!!
