### ISSUE TITLE
Sorry but how do you use percentage?

### ISSUE THREAD

**Issue by davidLpt** [colourgarden/avalanche#21]
Hi Tom, thank you for this great grid system.
I must have missed something but I can't get the percentage to work. I understood that i can't leave $av-width-class-namespace blank, but in the case I'd use 'col-' for exemple, let's say i want to set a div with 20% width, i have to give a 'col-20' class name to this div?

Thanks in advance for your help :)

**Comment by colourgarden** [comment]
Hi @davidLpt. Have you set `$av-width-class-style` to be `percentage`?

https://github.com/colourgarden/avalanche/blob/master/_avalanche.scss#L11

**Comment by davidLpt** [comment]
yes I did :)

here is the html i'm trying to output:

<div class="grid">
        <div class="col-20 grid__cell">
            <div class="box"></div>

```
    </div>
    <div class="col-40 grid__cell">
        <div class="box"></div>
    </div>
    <div class="col-40 grid__cell">
        <div class="box"></div>
    </div>
</div>
```

**Comment by colourgarden** [comment]
Could you please attach your settings file and compiled CSS so I can take a look?

**Comment by davidLpt** [comment]
ooohhh ok ok, i think i found my pb.... in the compiled css i have the followings classes:

`.col-50 { width: 50%;}
/* line 119, scss/vendors/avalanche/_avalanche.scss */
.col-33 {  width: 33.33333%;}
/* line 119, scss/vendors/avalanche/_avalanche.scss */
.col-66 {  width: 66.66667%;}
/* line 119, scss/vendors/avalanche/_avalanche.scss */
.col-25 {  width: 25%;}
/* line 119, scss/vendors/avalanche/_avalanche.scss */
.col-75 {  width: 75%;}`

But no col-40 or col-20...

which is probably due to these settings:
$av-widths: (
  2,
  3,
  4
)

**Comment by colourgarden** [comment]
You may need to add `5` to the `$av-widths` map. By default, Avalanche creates halves, thirds and quarters so 20% and 40% would not be included in that.

https://github.com/colourgarden/avalanche/blob/master/_avalanche.scss#L12-L16

**Comment by davidLpt** [comment]
absolutely, my bad my bad...... problem solved! Thank you for your help :)

**Comment by colourgarden** [comment]
No problem. Thanks for supporting Avalanche. Please do let me know if you have any live projects using the library - I'd love to see more examples of it being used in the wild!
