### ISSUE TITLE
Source ordering?

### ISSUE THREAD

**Issue by bellamystudio** [colourgarden/avalanche#26]
It would be great to have the ability to push and pull items based on breakpoints

eg push-1/4--medium, pull-1/2--medium

**Comment by bellamystudio** [comment]
OK I've hacked a way of doing this; adding these two class declarations straight after the 'create width class' block

```
        // Push/pull classes
        .pull--#{$class-name}{
            position:relative;
            left: -$width-value;
        }
        .push--#{$class-name}{
            position:relative;
            left: $width-value;
        }
```

**Comment by bellamystudio** [comment]
OK I've hacked a way

**Comment by colourgarden** [comment]
Hi @bellamystudio,

You can use the `grid--rev` class which flips the source order. To be honest, I've barely ever used push/pull classes when building UIs - my opinion being that if you need to move something 20/25/30% across the screen then a grid is possibly not the best solution to the problem - but if there's enough support for it then I'd be happy to include.

Please do share any use cases you have.

Thanks for taking an interest in Avalanche and for sharing your solution.
