### ISSUE TITLE
Grid --flush modifier

### ISSUE THREAD

**Issue by alesmenzel** [colourgarden/avalanche#29]
Question: Is there an option to make the grid cells flush with the grid wrapper but to keep inside gutter?

As on this picture:
http://prntscr.com/d6dxwp

**Comment by colourgarden** [comment]
Hi @AlesMenzel. This is the default behaviour of Avalanche. The grid wrapper had a negative left margin and then each cell has left padding so all grid cells are flush to the wrapper edges. Could you send a code sample?

Thanks for your interest in the project.

**Comment by alesmenzel** [comment]
Thanks! I just noticed I was overriding the margin property with other class... BTW the project seems very promising 👍 .
