### ISSUE TITLE
Any plans for flexbox/postcss?

### ISSUE THREAD

**Issue by Kurre** [colourgarden/avalanche#34]
Hi,

I really like your Grid Framework so far, but it left me wondering..

Do you have future plans regarding flexbox or maybe postcss?
Personally, I would love to see both of 'em 🙂

Or maybe something else in the back pocket?

**Comment by colourgarden** [comment]
Hi @Kurre. The next major step for Avalanche is to convert it to flexbox, yes. This is a pretty major undertaking which I just haven't had time to look at yet but I'm hoping to be able to get started on this soon. Please do contribute via a PR if this is something you feel you can help with.

**Comment by dezudas** [comment]
It will be great to have it in flex.
