### ISSUE TITLE
Grid Cell 100

### ISSUE THREAD

**Issue by jstewsy** [colourgarden/avalanche#35]
I have a use case where I need a grid cell to have a width of 50% `.grid__cell--50` for small devices and reset to `.grid__cell` or 100% width at medium.  

I didn't find any classes that were generated to handle this.

Would be nice to have class hooks for:
`.grid__cell--100-at-{breakpoint}`

**Comment by meowsus** [comment]
https://github.com/colourgarden/avalanche/blob/master/_avalanche.scss#L121

Looks like there's a specific case for a `$av-widths` list entry of 1.

**Comment by colourgarden** [comment]
@jstewsy This could be solved using a responsive breakpoint class on the cell. For example, `50--portable grid__cell`. [Example](https://codepen.io/anon/pen/LLeEPK). Does this solve it for you?
