### ISSUE TITLE
Unable to @extend a fractional class

### ISSUE THREAD

**Issue by valk** [colourgarden/avalanche#39]
I used an @extend directive in order to create a single class for multiple avalanche classes, like:

.my-class {
  @extend .1/4, .1/2--desk;   // rest of the attrs... 
}

The parser complains at the '/' character. To my understanding that's an illegal character for CSS classes, or am I missing something?

Thanks

**Comment by meowsus** [comment]
Did you try escaping?

```scss
@extend .1\/4, .1\/2--desk;
```

On compilation, that's what the library does to get around the illegal character.

**Comment by colourgarden** [comment]
As @meowsus says, you'll need to escape the slash characters but also the first number. So the following will work:

```
@extend .\31\/4, .\31\/2--desk;
```

This is certainly pretty ugly so you may wish to consider using the [`$av-width-class-namespace`](https://github.com/colourgarden/avalanche/blob/master/_avalanche.scss#L14) option to prefix the class names with an alpha character to make things a bit cleaner.

```
$av-width-class-namespace: 'w';

@import 'avalanche';

.test{
  @extend .w1\/4, .w1\/2--desk;
}
```

Or additionally use the `fragment` class style which will create classes like `.w1-of-4`...

```
$av-width-class-namespace: 'w';
$av-width-class-style: 'fragment';

@import 'avalanche';

.test{
  @extend .w1-of-4, .w1-of-2--desk;
}

```
