### ISSUE TITLE
Gutter problems

### ISSUE THREAD

**Issue by swthate** [colourgarden/avalanche#4]
Hi there,

I'm working on a small-ish landing page, and figured it'd be a good opportunity to try this!

I copied _avalanche.scss and got everything running. I have a "topbar" with two half-width grid cell's. It seems to be working nicely, but as I make the browser window smaller, the gutter "disappears" right as the topbar grid touches the edge of the browser window, if that makes sense.

The left padding on the grid-cell div basically goes off the page once that grid-cell div touches the side of the browser window.

I'm not sure what I could have done wrong?

**Comment by colourgarden** [comment]
Could you upload your code to [Codepen](http://codepen.io/) (or other similar service) so I can inspect?

Are you expecting a gutter on either side of the grid cells (giving you space on the sides on responsive view)? If you're used to the Bootstrap grid then Avalanche is a slightly different way of thinking. Avalanche has a [negative left margin on the grid row](https://github.com/colourgarden/avalanche/blob/master/_avalanche.scss#L149) equal to the gutter. This results in giving us true (in your case) 50% grid cell widths minus the gutter in the middle - nothing on the sides.

To add some space to the edges of the screen, you'd put a horizontal padding value on your container/wrapper div.
