### ISSUE TITLE
responsive layout

### ISSUE THREAD

**Issue by dezudas** [colourgarden/avalanche#42]
I tried 
1/6 1/3--portable 1/2--thumb grid__cell

it works well till portable but for thumb it can change the column size to 1/2

**Comment by colourgarden** [comment]
@dezudas Hi. Could you explain your issue a little more clearly? What is and isn't working; and what are you expecting to happen that isn't happening? Thanks

**Comment by dezudas** [comment]
@colourgarden I had a problem selecting the breaking points which if fixed. Is their any plan to move this to flex base??
